global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:${API_PORT}']
    metrics_path: /metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:${PROMETHEUS_PORT}']