model:
  architecture: "yolo11s.pt"  # Small model, better capacity for small objects
  img_size: 1280
  name: "object_detector_v1"

data:
  yaml_path: "./src/data/football_players_detection/data.yaml"
  train_path: "./src/data/football_players_detection/train/"
  val_path: "./src/data/football_players_detection/valid/"
  test_path: "./src/data/football_players_detection/test/"

training:
  batch_size: 12
  epochs: 300
  learning_rate: 0.0003
  lr_scheduler: cosine
  early_stopping_patience: 30
  freeze: [0,1,2]          # Freeze backbone stages; prevents overwriting pretrained features


device: "cuda:0"  # Maps to physical GPU set by CUDA_VISIBLE_DEVICES

output:
  project_dir: "../runs_detect"
  model_dir: "../models"


mlflow:
  tracking_uri: "http://localhost:5000"  # Local for dev
  experiment_name: "object_detection"

wandb:
  enabled: false
  project: "object-detection-mlops"