model:
  architecture: "yolo11n.pt"  # Medium model for balance
  img_size: 640
  name: "object_detector_v1"

data:
  yaml_path: "./src/data/football_players_detection/data.yaml"
  train_path: "./src/data/football_players_detection/train/"
  val_path: "./src/data/football_players_detection/valid/"
  test_path: "./src/data/football_players_detection/test/"

training:
  batch_size: 32           
  epochs: 100               
  learning_rate: 0.0003    
  lr_scheduler: cosine     
  early_stopping_patience: 7   
  freeze: [0,1,2]          # Freeze backbone stages; prevents overwriting pretrained features


device: "cuda:1"  # or "cpu" for local testing

output:
  project_dir: "../runs_detect"
  model_dir: "../models"


mlflow:
  tracking_uri: "http://localhost:5000"  # Local for dev
  experiment_name: "object_detection"

wandb:
  enabled: false
  project: "object-detection-mlops"